In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
crimes_df = pd.read_csv('../../data/crimes.dataset.csv')

In [3]:
crimes_df

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape\n(revised\ndefinition),Rape\n(revised\ndefinition)\nrate,Rape\n(legacy\ndefinition,Rape\n(legacy\ndefinition)\nrate,...,Aggravated\nassault,Aggravated\nassault rate,Property\ncrime,Property\ncrime\nrate,Burglary,Burglary\nrate,Larceny-\ntheft,Larceny-\ntheft rate,Motor\nvehicle\ntheft,Motor\nvehicle\ntheft\nrate
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,...,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,...,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,...,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,...,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,...,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,...,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,...,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,...,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,...,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,...,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,...,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,...,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,...,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,...,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,...,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,...,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,...,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,...,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,...,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,...,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

In [4]:
crimes_df=crimes_df.rename(columns={'Rape\n(revised\ndefinition)':'Rape_revised','Rape\n(revised\ndefinition)\nrate':'Rape_revised_rate', 'Rape\n(legacy\ndefinition':'Rape', 'Rape\n(legacy\ndefinition)\nrate': 'Rape_rate'})
crimes_df

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,...,Aggravated\nassault,Aggravated\nassault rate,Property\ncrime,Property\ncrime\nrate,Burglary,Burglary\nrate,Larceny-\ntheft,Larceny-\ntheft rate,Motor\nvehicle\ntheft,Motor\nvehicle\ntheft\nrate
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,...,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,...,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,...,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,...,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,...,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,...,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,...,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,...,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,...,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,...,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,...,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,...,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,...,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,...,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,...,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,...,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,...,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,...,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,...,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,...,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
crimes_df

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery\nrate,Aggravated\nassault,Aggravated\nassault rate,Property\ncrime,Property\ncrime\nrate,Burglary,Burglary\nrate,Larceny-\ntheft,Larceny-\ntheft rate,Motor\nvehicle\ntheft,Motor\nvehicle\ntheft\nrate
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

In [7]:
crimes_df=crimes_df.rename(columns={'Robbery\nrate':'Robbery_rate','Aggravated\nassault':'Aggravated_assault', 'Aggravated\nassault rate':'Aggravated_assault_rate', 'Property\ncrime': 'Property_crime','Property\ncrime\nrate':'Property_crime_rate','Burglary\nrate':'Burglary_rate', 'Larceny-\ntheft':'Larceny_theft','Larceny-\ntheft rate':'Larceny_theft_rate','Motor\nvehicle\ntheft':'Motor_vehicle_theft','Motor\nvehicle\ntheft\nrate':'Motor_vehicle_theft_rate'})
crimes_df

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

In [8]:
crimes_highest=crimes_df.sort_values(by=['Violent crime rate'], ascending=False)
crimes_highest

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4

## 2000 had the highest violent crime rate, but 2001 had the highest number of violent crimes.

In [9]:
crimes_highestmurder=crimes_df.sort_values(by=['Murder nonnegligent manslaughter'], ascending=False)
crimes_highestmurder

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4

In [10]:
crimes_highestmurder_rate=crimes_df.sort_values(by=['Murder nonnegligent manslaughter rate'], ascending=False)
crimes_highestmurder_rate

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4

## 2016 had the highest murder count, but 2006 had the highest murder rate

In [11]:
crimes_highestrobbery=crimes_df.sort_values(by=['Robbery'], ascending=False)
crimes_highestrobbery

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

In [12]:
crimes_highestrobbery_rate=crimes_df.sort_values(by=['Robbery_rate'], ascending=False)
crimes_highestrobbery_rate

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

## 2006 had the highest robbery rate and number of robberies

In [13]:
crimes_highestassault=crimes_df.sort_values(by=['Aggravated_assault'], ascending=False)
crimes_highestassault

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3

In [14]:
crimes_highestassault_rate=crimes_df.sort_values(by=['Aggravated_assault_rate'], ascending=False)
crimes_highestassault_rate

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4

## 2000 had the highest number of Assaults and the highest Assault rate

In [16]:
crimes_highestprop=crimes_df.sort_values(by=['Property_crime'], ascending=False)
crimes_highestprop

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2

In [19]:
crimes_highestprop_rate=crimes_df.sort_values(by=['Property_crime_rate'], ascending=False)
crimes_highestprop_rate

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

## 2007 had the most property crimes and 2001 had the highest rate for property crimes.

In [20]:
crimes_highestburglary=crimes_df.sort_values(by=['Burglary'], ascending=False)
crimes_highestburglary

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

In [21]:
crimes_highestburglary_rate=crimes_df.sort_values(by=['Burglary_rate'], ascending=False)
crimes_highestburglary_rate

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

## 2008 had the most burglaries and 2002 had the highest burglary rate

In [22]:
crimes_highestlarceny=crimes_df.sort_values(by=['Larceny_theft'], ascending=False)
crimes_highestlarceny

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

In [23]:
crimes_highestlarceny_rate=crimes_df.sort_values(by=['Larceny_theft_rate'], ascending=False)
crimes_highestlarceny_rate

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9

## 2001 had the most larceny thefts and the highest rate for larceny thefts

In [24]:
crimes_highestmotor=crimes_df.sort_values(by=['Motor_vehicle_theft'], ascending=False)
crimes_highestmotor

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9

In [25]:
crimes_highestmotor_rate=crimes_df.sort_values(by=['Motor_vehicle_theft_rate'], ascending=False)
crimes_highestmotor_rate

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4

## 2008 had the most motor vehicle thefts and 2003 had the highest rate of motor vehicle thefts.

## 2001 had the most problems with the most violent crimes, the highest property crimes rate, the most larceny thefts, and the highest larceny theft rate.

## 2000 and 2006 each appeared 3 times. 2000 had the highest violent crime rate, the most assaults, and the highest assault rate. 200 had the highest number of robberies, the highest robbery rate, and the highest murder rate.

In [26]:
crimes_pop=crimes_df.sort_values(by=['Population'], ascending=False)
crimes_pop

,Year,Population,Violent Crimes,Violent crime rate,Murder nonnegligent manslaughter,Murder nonnegligent manslaughter rate,Rape_revised,Rape_revised_rate,Rape,Rape_rate,Robbery,Robbery_rate,Aggravated_assault,Aggravated_assault_rate,Property_crime,Property_crime_rate,Burglary,Burglary_rate,Larceny_theft,Larceny_theft_rate,Motor_vehicle_theft,Motor_vehicle_theft_rate
19,2019,"328,239,523","1,203,808",366.7,"16,425",5.0,"139,815",42.6,"98,213",29.9,"267,988",81.6,"821,182",250.2,"6,925,677","2,109.9","1,117,696",340.5,"5,086,096","1,549.5","721,885",219.9
18,2018,"326,687,501","1,209,997",370.4,"16,374",5.0,"143,765",44.0,"101,363",31.0,"281,278",86.1,"810,982",248.2,"7,219,084","2,209.8","1,235,013",378.0,"5,232,167","1,601.6","751,904",230.2
17,2017,"325,147,121","1,247,917",383.8,"17,294",5.3,"135,666",41.7,"99,708",30.7,"320,596",98.6,"810,319",249.2,"7,682,988","2,362.9","1,397,045",429.7,"5,513,000","1,695.5","772,943",237.7
16,2016,"323,405,935","1,250,162",386.6,"17,413",5.4,"132,414",40.9,"96,970",30.0,"332,797",102.9,"802,982",248.3,"7,928,530","2,451.6","1,516,405",468.9,"5,644,835","1,745.4","767,290",237.3
15,2015,"320,896,618","1,199,310",373.7,"15,883",4.9,"126,134",39.3,"91,261",28.4,"328,109",102.2,"764,057",238.1,"8,024,115","2,500.5","1,587,564",494.7,"5,723,488","1,783.6","713,063",222.2
14,2014,"318,907,401","1,153,022",361.6,"14,164",4.4,"118,027",37.0,"84,864",26.6,"322,905",101.3,"731,089",229.2,"8,209,010","2,574.1","1,713,153",537.2,"5,809,054","1,821.5","686,803",215.4
13,2013,"316,497,531","1,168,298",369.1,"14,319",4.5,"113,695",35.9,"82,109",25.9,"345,093",109.0,"726,777",229.6,"8,651,892","2,733.6","1,932,139",610.5,"6,019,465","1,901.9","700,288",221.3
12,2012,"313,873,685","1,217,057",387.8,"14,856",4.7,NaN,NaN,"85,141",27.1,"355,051",113.1,"762,009",242.8,"9,001,992","2,868.0","2,109,932",672.2,"6,168,874","1,965.4","723,186",230.4
11,2011,"311,587,816","1,206,005",387.1,"14,661",4.7,NaN,NaN,"84,175",27.0,"354,746",113.9,"752,423",241.5,"9,052,743","2,905.4","2,185,140",701.3,"6,151,095","1,974.1","716,508",230.0
10,2010,"309,330,219","1,251,248",404.5,"14,722",4.8,NaN,NaN,"85,593",27.7,"369,089",119.3,"781,844",252.8,"9,112,625","2,945.9","2,168,459",701.0,"6,204,601","2,005.8","739,565",239.1
9,2009,"307,006,550","1,325,896",431.9,"15,399",5.0,NaN,NaN,"89,241",29.1,"408,742",133.1,"812,514",264.7,"9,337,060","3,041.3","2,203,313",717.7,"6,338,095","2,064.5","795,652",259.2
8,2008,"304,059,724","1,394,461",458.6,"16,465",5.4,NaN,NaN,"90,750",29.8,"443,563",145.9,"843,683",277.5,"9,774,152","3,214.6","2,228,887",733.0,"6,586,206","2,166.1","959,059",315.4
7,2007,"301,621,157","1,422,970",471.8,"17,128",5.7,NaN,NaN,"92,160",30.6,"447,324",148.3,"866,358",287.2,"9,882,212","3,276.4","2,190,198",726.1,"6,591,542","2,185.4","1,100,472",364.9
6,2006,"299,398,484","1,435,123",479.3,"17,309",5.8,NaN,NaN,"94,472",31.6,"449,246",150.0,"874,096",292.0,"10,019,601","3,346.6","2,194,993",733.1,"6,626,363","2,213.2","1,198,245",400.2
5,2005,"296,507,061","1,390,745",469.0,"16,740",5.6,NaN,NaN,"94,347",31.8,"417,438",140.8,"862,220",290.8,"10,174,754","3,431.5","2,155,448",726.9,"6,783,447","2,287.8","1,235,859",416.8
4,2004,"293,656,842","1,360,088",463.2,"16,148",5.5,NaN,NaN,"95,089",32.4,"401,470",136.7,"847,381",288.6,"10,319,386","3,514.1","2,144,446",730.3,"6,937,089","2,362.3","1,237,851",421.5
3,2003,"290,788,976","1,383,676",475.8,"16,528",5.7,NaN,NaN,"93,883",32.3,"414,235",142.5,"859,030",295.4,"10,442,862","3,591.2","2,154,834",741.0,"7,026,802","2,416.5","1,261,226",433.7
2,2002,"287,973,924","1,423,677",494.4,"16,229",5.6,NaN,NaN,"95,235",33.1,"420,806",146.1,"891,407",309.5,"10,455,277","3,630.6","2,151,252",747.0,"7,057,379","2,450.7","1,246,646",432.9
1,2001,"285,317,559","1,439,480",504.5,"16,037",5.6,NaN,NaN,"90,863",31.8,"423,557",148.5,"909,023",318.6,"10,437,189","3,658.1","2,116,531",741.8,"7,092,267","2,485.7","1,228,391",430.5
0,2000,"281,421,906","1,425,486",506.5,"15,586",5.5,NaN,NaN,"90,178",32.0,"408,016",145.0,"911,706",324.0,"10,182,584","3,618.3","2,050,992",728.8,"6,971,590","2,477.3","1,160,002",412.2

## The population steadily increases from 2000 to 2019